BEGIN TRANSACTION;
-- MARYLIN MONROE
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(1,12,'IDADE PERIGOSA',1947);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(2,29,'LOUCOS DE AMOR',1949);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(3,12,'POR UM  AMOR',1950);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(4,14,'RIO SEM REGRESSO',1954);
-- URSULA ANDRESS
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(5,13,'JAMES BOND 007 - CASINO ROYALE',1967);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(6,12,'CREPUSCULO DAS AGUIAS',1966);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(7,13,'007 - CONTRA O SATÂNICO DR NO',1962);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(8,21,'FUN IN ACAPULCO',1963);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(9,15,'FURIA DE TITÃS',1981);
--CATE BLANCHET
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(10,13,'O SENHOR DOS ANÉIS - AS DUAS TORRES',2002);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(11,21,'O SENHOR DOS ANÉIS - A SOCIEDADE DO ANEL',2001);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(12,15,'O SENHOR DOS ANÉIS - O RETORNO DO REI',2003);
--INGRID BERGMANN
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(13,8,'MAIS UMA VEZ ADEUS',1933);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(14,12,'CASABLANCA',1942);
--JODIE FOSTER
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(15,12,'TAXI DRIVER',1976);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(16,24,'THE SIMPSONS',2009);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(17,24,'ARQUIVO X',1997);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(18,12,'CARNAGE',2003);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(19,12,'VALENTE',2007);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(20,4,'NEBLINA E SOMBRAS',1992);
--SCARLET JOHANSSON
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(21,17,'A ILHA',2005);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(22,2,'VIUVA NEGRA',2021);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(23,24,'JOJO RABBIT ',2019);
--MERYL STREEP
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(24,29,'MAMA MIA - O FILME',2008);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(25,7,'LIGADO EM VOCÊ',2003);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(26,17,'O DOADOR DE MEMÓRIAS ',2014);
--TOM HANKS
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(27,22,'O CÓDIGO DA VINCI',2006);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(28,17,'ANJOS E DEMÔNIOS',2009);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(29,17,'INFERNO ',2016);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(30,7,'FOREST GUMP: O CONTADOR DE HISTÓRIAS',1994);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(31,12,'CAPITÃO PHILIPS',2013);
--DENZEL WASHINGTON
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(32,1,'O PROTETOR: SEM MISERICÓRDIA',2014);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(33,1,'O PROTETOR 2: A VINGANÇA',2018);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(34,28,'DEJA VU',2006);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(35,12,'O VOO',2012);
--SEAN CONNERY
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(36,2,'A LIGA EXTRAORDINÁRIA',2003);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(37,2,'INDIANA JONES E A ULTIMA CRUSADA',1989);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(38,1,'A ROCHA ',1996);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(39,13,'007: CONTRA A CHANTAGEM ATÔMICA',1965);
-- HARISON FORD
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(40,2,'INDIANA JONES E A ULTIMA CRUSADA',1989);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(41,2,'INDIANA JONES 5',2022);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(42,2,'INDIANA JONES E O REINO DA CAVEIRA DE CRISTAL ',2008);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(43,2,'INDIANA JONES E O TEMPLO DA PERDIÇÃO',1984);
-- ROBERT DE NIRO
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(44,12,'CORINGA',2019);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(45,12,'O IRLANDÊS',2019);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(46,8,'ULTIMA VIAGEM A VEGAS ',2013);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(47,15,'STURDUST: O MISTÉRIO DA ESTRELA CADENTE',2007);
--AL PACINO
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(48,12,'PERFUME DE MULHER',1992);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(49,12,'ADVOGADO DO DIABO',1997);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(50,22,'O PAGAMENTO FINAL',1993);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(51,22,'FOGO CONTRA FOGO',1995);
--JACK NICKOLSON
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(52,12,'ANTES DE PARTIR',2007);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(53,1,'BATMAN',1989);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(54,4,'TRATAMENTO DE CHOQUE ',2003);
INSERT INTO FILMES (COD_FILME,COD_GENERO,TITULO,ANO) VALUES(55,8,'COMO VOCÊ SABE',2010);
COMMIT;