BEGIN TRANSACTION;
--JACK NICOLSON
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (52,1,12);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (53,1,1);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (54,1,4);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (55,1,8);
--AL PACINO
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (48,2,12);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (49,2,12);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (50,2,22);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (51,2,22);
-- ROBERT DE NIRO
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (44,3,12);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (45,3,12);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (46,3,22);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (47,3,22);
-- HARISON FORD
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (40,4,2);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (41,4,2);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (42,4,2);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (43,4,2);
--SEAN CONNERY
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (36,5,2);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (37,5,2);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (38,5,1);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (39,5,13);
--DENZEL WASHINGTON
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (32,6,1);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (33,6,1);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (34,6,28);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (35,6,12);
--TOM HANKS
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (27,7,22);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (28,7,22);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (29,7,17);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (30,7,7);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (31,7,12);
--MERYL STREEP
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (24,8,29);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (25,8,7);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (26,8,17);
--SCARLET JOHANSSON
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (21,9,17);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (22,9,2);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (23,9,24);
--JODIE FOSTER
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (15,10,12);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (16,10,24);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (17,10,24);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (18,10,12);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (19,10,12);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (20,10,4);
--INGRID BERGMANN
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (13,11,8);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (14,11,12);
--CATE BLANCHET
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (10,12,13);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (11,12,21);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (12,12,15);
-- URSULA ANDRESS
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (5,13,13);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (6,13,12);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (7,13,13);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (8,13,21);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (9,13,15);
-- MARYLIN MONROE
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (1,14,12);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (2,14,29);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (3,14,12);
INSERT INTO FILME_ATOR (COD_FILME,COD_ATOR_PRINCIPAL,COD_GENERO) VALUES (4,14,14);
COMMIT;